### ISSUE TITLE
suggestion: add "Why" to Readme

### ISSUE THREAD

**Issue by hugosenari** [juancarlospaco/cpython#1]
As a _developer_
I want _known why_
So that I can _decide if I should use it or not_

My own experience: I could only realize why you did it, when you mention nodejs lib, maybe for someone without that previous knowledge it would be harder.

Nice related content: https://sketchplanations.com/the-golden-circle

Sorry it should be a pull request, but I'm not confident with my English neither the why or pros/cons, of use your lib.

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/cpython#why  ?.

I will try to expand that section of the readme. 🙂
