### ISSUE TITLE
theindex.html (and search) doesn't work

### ISSUE THREAD

**Issue by timotheecour** [juancarlospaco/cpython#2]
eg https://juancarlospaco.github.io/cpython/theindex.html gives 404

also, with such working index you wouldn't neeed to maintain a (manually generated?) README with the docs which does essentially the same;

## example
see how other packages handle this, eg:

* https://github.com/nitely/nim-regex => "Read the docs" https://nitely.github.io/nim-regex/regex.html
* https://github.com/citycide/glob
* https://github.com/kaushalmodi/std_vector

**Comment by juancarlospaco** [comment]
And "See Source" link, I never remember the command line to generate all those. 😧

**Comment by timotheecour** [comment]
> And "See Source" link, I 

i was just about to add that; ya; see kochdocs.nim for how it's done

**Comment by juancarlospaco** [comment]
Note for devs, see https://github.com/juancarlospaco/nodejs/blob/main/.github/workflows/build.yml#L37

**Comment by juancarlospaco** [comment]
@timotheecour
I tried, but it looks like it can only document code in a `devel` branch, 
it generates URLs for `/tree/devel/src/`, and I do not use that branch name, so yeah not easy to do...
