### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by timotheecour** [juancarlospaco/cpython#3]
* how did you generate the APIS? nimterop? (obviously not c2nim ...)
* how is this maintained/kept up to date?
* syntax highlight is broken eg https://github.com/juancarlospaco/cpython/blob/nim/src/cpython/base64.nim
* > Same API as Python StdLib, same function names, same argument names.
=> maybe give more details (eg regarding how trailing `_` are handled, since illegal ... for now)

* > It does not use anything from Nim standard library, very future-proof.

this needs clarification, because it uses nimpy (which itself uses stdlib)
* nimpy (which is the thing that makes it all work) should be clearly mentioned (with a link also) in the README

**Comment by juancarlospaco** [comment]
> how did you generate the APIS? 

> it uses nimpy

I do not understand, you are replying to yourself.

> regarding how trailing _ are handled, since illegal 

And thats the reason why it should be legalized.

> It does not use anything from Nim standard library

Kinda true, code in the repo does not use too much stdlib.
Nimpy does, but thats not on this repo, nor is my code.
Whatsoever compiler uses stdlib to compile itself too, but again thats not in this repo etc,
I dont know how to make it more explicit.

**Comment by timotheecour** [comment]
> And thats the reason why it should be legalized.

but until it's legalized (which may or not happen), the question is how do you map illegal name to legal name; it should be documented

> I do not understand, you are replying to yourself.

my question is whether you use some automated way to generate the list of APIs (and their types etc) or generate those by hand; I know you're using nimpy but AFAIK nimpy doesn't help with generating the list of APIs in a python module, or does it?

> I dont know how to make it more explicit.

"the generated APIs use nimpy (https://github.com/yglukhov/nimpy) to make python-nim interop work, but other than that the wrappers are thin wrappers, resulting in a minimal dependency on nim's stlib"

**Comment by juancarlospaco** [comment]
No one tries to hide this is all thanks to Nimpy.
https://github.com/juancarlospaco/cpython/blob/nim/cpython.nimble#L9

Maybe thats just myself... 
when I want to know the dependencies of a project I just look at the `.nimble` file, and I think thats a good practice,
because is very explicit and literal, and doc may be lacking or outdated, wording and spoken language, etc.

**Comment by juancarlospaco** [comment]
Added to readme what you said literally.

**Comment by juancarlospaco** [comment]
Python API is from official Python Docs.

**Comment by juancarlospaco** [comment]
I hope that responds the question... 🙂:+1:
