### ISSUE TITLE
boilerplate should be refactored

### ISSUE THREAD

**Issue by timotheecour** [juancarlospaco/cpython#4]
these appear in each module (with minor modifications):
```nim
template X(simbol):       auto = nimpy.pyImport("crypt").simbol().to(type(result))
template X(simbol; a):    auto = nimpy.pyImport("crypt").simbol(a).to(type(result))
template X(simbol; a, b): auto = nimpy.pyImport("crypt").simbol(a, b).to(type(result))
```
can you instead add a private module `pyutils` which you import in each module, possibly with a macro eg:
```nim
# pyutils.nim:
macro genWrappers*(name: string) =
  template X(simbol):       auto = nimpy.pyImport(name).simbol().to(type(result))
  template X(simbol; a):    auto = nimpy.pyImport(name).simbol(a).to(type(result))
  template X(simbol; a, b): auto = nimpy.pyImport(name).simbol(a, b).to(type(result))

# in crypt.nim:
import pyutils
genWrappers("crypt")

...
```

**Comment by juancarlospaco** [comment]
It started with an editor plugin that pastes a boilerplate snippet on each new file,
and people liked the idea that you can just copy 1 file into your project and use it,
also line count per file is low kinda <200 lines per file so is not thaat much,
aaalso not all of the boilerplate is exactly the same they have tiny differences,
but yeah having some kind of private `include "prelude.nim"` for the project would be nice too.

**Comment by juancarlospaco** [comment]
For simplicity, for now, we stay with the boilerplate.
