### ISSUE TITLE
Add tkinter module.

### ISSUE THREAD

**Issue by kalbhairab** [juancarlospaco/cpython#5]
>

**Comment by juancarlospaco** [comment]
Instead of Tkinter, which no one uses in Python..., 
I think instead wrap IUP thats very simple tiny API, with just function calls,
or instead go big, and wrap PyQt6, but is huge.
🤔

**Comment by juancarlospaco** [comment]
We added initial support for UPBGE maybe you can use it to make 2D/3D GUI, games and more:
https://github.com/juancarlospaco/cpython/tree/nim/src/cpython/upbge
