### ISSUE TITLE
actual Nim code?

### ISSUE THREAD

**Issue by kobi2187** [juancarlospaco/cpython#7]
Looking at the source, this is just using python under the hood,
so same performance characteristics.

The project is laudable, but why not replace at least the obvious parts with Nim code?
Then it would make ported python that use your library much faster.

**Comment by juancarlospaco** [comment]
I do not understand what do you mean, 
this project "hijacks Python StdLib for Nim" is basically what it does, make Python libs usable from Nim,
it is not about Nim code that mimics Python, that already exists (I contributed to it):
https://github.com/Yardanico/nimpylib

**Comment by kobi2187** [comment]
sorry, didn't know about pylib.
